apiVersion: v1
kind: ReplicationController
metadata:
  name: springboot-rd-data-contoller
spec:
  replicas: 3
  selector:
    app: springboot-rd-data
  template:
    metadata:
     labels:
       app: springboot-rd-data
    spec:
     containers:
     - name: springboot-rd-data
       image: lilingcheng/springboot-rd-data
       ports:
       - containerPort: 30728
     nodeSelector:
       zone:  read-write


