apiVersion: v1
kind: Pod
metadata:
  name: springboot-data
  labels:
    app: springboot-data
spec:
  containers:
  - name: springboot-data
    image: lilingcheng/springboot-data
    ports:
    - containerPort: 30727
  nodeSelector:
    zone: read-write
