apiVersion: v1
kind: Service
metadata:
  name: springboot-data-service
  labels:
    app: springboot-data
spec:
  type: NodePort
  ports:
  - port: 30727
    targetPort: 30727
    nodePort: 30723
  selector:
    app: springboot-data
