apiVersion: v1
kind: Service
metadata:
  name: springboot-rd-data-service
  labels:
    app: springboot-rd-data
spec:
  type: NodePort
  ports:
  - port: 30728
    targetPort: 30728
    nodePort: 30724
  selector:
    app: springboot-rd-data
